@SmartLocker.Api_HostAddress = http://localhost:5231

@token = InserteToken

GET {{SmartLocker.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

### Crear locker
POST https://localhost:7177/api/lockers
Content-Type: application/json
Accept: application/json

{
  "codigo": "L-006",
  "ubicacion": "Planta 5",
  "estado": "Disponible",
  "tamano": "Pequeño"
}

###

### Eliminar locker
DELETE https://localhost:7177/api/lockers/6

###

### Actualizar locker
PUT https://localhost:7177/api/lockers/6
Content-Type: application/json
Accept: application/json

{
  "codigo": "L-006",
  "ubicacion": "Planta 6",
  "estado": "Ocupado",
  "tamano": "Grande"
}

### Crear locker inválido
POST https://localhost:7177/api/lockers
Content-Type: application/json
Accept: application/json

{
  "codigo": "",
  "ubicacion": "",
  "estado": "Disponible",
  "tamano": "Mediano"
}

### Obtener lockers
GET https://localhost:7177/api/lockers
Accept: application/json

### Login
POST https://localhost:7177/api/auth/login
Accept: application/json

  ### GET lockers con token
GET https://localhost:7177/api/lockers
Accept: application/json
Authorization: Bearer {{token}}

### Login correcto
POST https://localhost:7177/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "1234"
}

  ### Login incorrecto
POST https://localhost:7177/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "incorrecta"
}

### Login sin password
POST https://localhost:7177/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin"
}